apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-pod
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      initContainers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'until nslookup service-nginx.default.svc.cluster.local; do echo "Waiting for service-nginx"; sleep 2; done']