apiVersion: v1
kind: Service
metadata:
  name: svc-mp
spec:
  selector:
    app: my-app
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: mt-port
      protocol: TCP
      port: 9002
      targetPort: 8080
    