apiVersion: v1
kind: Service
metadata:
  name: svc-np
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 31081
    - name: mt-port
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 31082