---
# tasks file for clickhouse
- block:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        dest: "./{{ item }}_{{ clickhouse_version }}_amd64.deb"
      with_items: "{{ clickhouse_packages }}"
  rescue:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
        dest: "./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
- name: Install clickhouse client
  become: true
  ansible.builtin.apt:
    deb: /home/galchonkov/clickhouse-client_22.8.5.29_amd64.deb
    state: present
    update_cache: yes
  notify: Start clickhouse service
- name: Install clickhouse server
  become: true
  ansible.builtin.apt:
    deb: /home/galchonkov/clickhouse-server_22.8.5.29_amd64.deb
    state: present
    update_cache: yes
  notify: Start clickhouse service
- name: Install clickhouse common-static
  become: true
  ansible.builtin.apt:
    deb: /home/galchonkov/clickhouse-common-static_22.8.5.29_amd64.deb
    state: present
    update_cache: yes
  notify: Start clickhouse service
- name: Flush handlers to restart clickhouse
  ansible.builtin.meta: flush_handlers
- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  become: true
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0