---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.101.133
    jenkins-agent-01:
      ansible_host: 51.250.78.212
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection: ssh
    ansible_user: galchonkov
    ansible_ssh_private_key_file: /home/galchonkov/.ssh/id_ed25519